apiVersion: v1
kind: Service
metadata:
  name: eks-service
spec:
  selector:
    app: eks-service
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: eks-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: eks-service
  template:
    metadata: 
      labels: 
        app: eks-service
    spec:
      containers:
      - name: eks-service
        image: manojfst88/eks-service:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: dockerhubcred

      